### ISSUE TITLE
Build and Deploy happens too often -> reduce to daily...

### ISSUE THREAD

**Issue by ff2u** [WeAreFairphone/fpangels-hp#13]
From my point of view it'd be sufficient to have Build and Deploy run only daily (not hourly). Changes of the homepage source are very rare and so it's not needed to re-create the FPAngels HP so often.
It'd save resources and energy to run it only on a daily basis (and sustainability is one of the basic Fairphone principles...).

**Comment by Ryuno-Ki** [comment]
Looking at the Insights Tab, you could even switch to weekly, if you build from the source code in here.

**Comment by ff2u** [comment]
I think weekly is too seldom as you newer know when FP Angels source page is updated. And it should not be necessary to wait up to one week to see then changes in the home page once it's updated...

**Comment by Ryuno-Ki** [comment]
Oh. My understanding was, that there are some API requests that might need regular updates.
If an Angel updates the source, I would expect a new build to be created on merge into the master branch.

**Comment by ff2u** [comment]
The angels data source file is not located on github but within the Fairphone forum. So there's no merge possible.

**Comment by Ingo-FP-Angel** [comment]
An alternative would be to not schedule the build and deploy at all but use `workflow_dispatch` as trigger, i.e. manually run it whenever the input changes.

Or maybe it could be an additional trigger so that the scheduled interval can be rather long, but if someone needs the changes reflected sooner than that they can always press a button.

**Comment by ff2u** [comment]
It's now done on a daily basis. The proposed alternatives can still be coded by someone able to do it... :smile:
