### ISSUE TITLE
Smartphones display homepage in full width

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fpangels-hp#2]

**Comment by StefanBrand** [comment]
Can probably be solved by adding `<meta name="viewport" content="width=device-width">` to the `head`.

**Comment by ff2u** [comment]
Yes, this header seems to solve the problem as can be seen on a test page containing this meta tag at
https://ff2u.github.io/

**Comment by ff2u** [comment]
Header line <meta name="viewport" content="width=device-width"> has been added as proposed by @StefanBrand . Now Smartphones display homepage in full width.
